# Generated by Django 4.2.6 on 2023-11-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='所在省份')),
                ('population', models.PositiveIntegerField(verbose_name='人口体量')),
                ('resources', models.TextField(verbose_name='资源禀赋')),
                ('industry', models.CharField(max_length=50, verbose_name='主要产业')),
                ('terrain', models.CharField(max_length=50, verbose_name='地形')),
                ('village_size', models.CharField(max_length=50, verbose_name='村庄规模')),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='年平均收入')),
            ],
        ),
        migrations.CreateModel(
            name='ExcellentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='案例标题')),
                ('experience', models.TextField(verbose_name='经验描述')),
                ('village_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excellentCase.villageinfo', verbose_name='关联村庄信息')),
            ],
        ),
    ]
