# Generated by Django 4.2.6 on 2023-11-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excellentCase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellentcase',
            name='category',
            field=models.CharField(choices=[('industrial', '产业振兴'), ('talent', '人才振兴'), ('cultural', '文化振兴'), ('ecological', '生态振兴'), ('organizational', '组织振兴')], default='industrial', max_length=20, verbose_name='案例分类'),
        ),
        migrations.AddField(
            model_name='villageinfo',
            name='village_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='村庄名称'),
        ),
    ]
