# Generated by Django 4.2.6 on 2023-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excellentCase', '0002_excellentcase_category_villageinfo_village_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellentcase',
            name='description',
            field=models.CharField(default='我是优秀案例的简短说明。', max_length=200, verbose_name='案例简短说明'),
        ),
    ]
